#!/usr/bin/env bash
#
# Apply the Tetris-specific changes on top of a synced LineageOS 24.0 tree.
# Run from the top of the source tree, after every `repo sync`.
#
#   1. Retarget device/nothing/Tetris from BlissROMs to LineageOS.
#   2. `git am` every patches/<project path>/*.patch into that project.
#
# Each change is recorded as a local commit, so the next `repo sync` discards
# it cleanly ("discarding N commits") and a re-run of this script re-applies it.
# Re-running without a sync is safe: anything already applied is skipped.
#
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOP="$PWD"
DT_REL="device/nothing/Tetris"
DT="$TOP/$DT_REL"

die()  { echo "apply-patches: ERROR: $*" >&2; exit 1; }
info() { echo "apply-patches: $*"; }
g()    { local proj=$1; shift; (cd "$TOP/$proj" && git "$@"); }   # git inside a project

[[ -d "$TOP/.repo" ]] || die "run this from the top of the source tree (no .repo/ in $TOP)"

# The local commits need a committer identity. Use the configured one if any;
# otherwise a neutral local value. Patch authors are preserved by `git am`.
# No git config is written.
if ! git config --get user.email >/dev/null 2>&1; then
    export GIT_AUTHOR_NAME="Tetris build" GIT_AUTHOR_EMAIL="build@localhost"
    export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME" GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
fi

retarget_device_tree() {
    [[ -e "$DT/.git" ]] || die "$DT_REL is missing - did repo sync pick up tetris.xml?"

    # Start from a clean tree, so a failed check below can roll back to HEAD
    # without touching anyone's work, and "already done" is never a half-done tree.
    [[ -z "$(g "$DT_REL" status --porcelain)" ]] \
        || die "$DT_REL has uncommitted changes - commit or stash them, then re-run"

    if grep -q 'lineage_Tetris\.mk' "$DT/AndroidProducts.mk"; then
        info "$DT_REL already targets LineageOS - skipped"
        return
    fi

    local src="$DT/bliss_Tetris.mk"
    [[ -f "$src" ]] || die "expected $DT_REL/bliss_Tetris.mk - upstream renamed its product makefile; update this script"

    # Derive lineage_Tetris.mk from upstream's own makefile on every run, so a
    # firmware bump upstream (build fingerprint etc.) carries over automatically.
    sed -e 's#vendor/bliss/config/common_full_phone\.mk#vendor/lineage/config/common_full_phone.mk#' \
        -e 's#^\# Inherit some common BlissRoms stuff\.#\# Inherit some common LineageOS stuff.#' \
        -e '/^BLISS_BUILDTYPE[[:space:]]*:=/d' \
        -e '/^EXTRA_UDFPS_ANIMATIONS[[:space:]]*:=/d' \
        -e '/^GAPPS_ARCH[[:space:]]*:=/d' \
        -e 's#^PRODUCT_NAME := bliss_Tetris$#PRODUCT_NAME := lineage_Tetris#' \
        "$src" > "$DT/lineage_Tetris.mk"

    sed -i.orig 's#\$(LOCAL_DIR)/bliss_Tetris\.mk#$(LOCAL_DIR)/lineage_Tetris.mk#' "$DT/AndroidProducts.mk"
    sed -i.orig \
        -e 's#vendor/bliss/config/BoardConfigReservedSize\.mk#vendor/lineage/config/BoardConfigReservedSize.mk#' \
        -e 's#device/bliss/sepolicy/libion/sepolicy\.mk#device/lineage/sepolicy/libion/sepolicy.mk#' \
        "$DT/BoardConfig.mk"
    rm -f "$DT/AndroidProducts.mk.orig" "$DT/BoardConfig.mk.orig"
    g "$DT_REL" rm -q bliss_Tetris.mk

    # Fail closed: a Bliss path left anywhere would only surface hours later as a
    # make error. On any failure, put the tree back exactly as it was.
    fail() {
        g "$DT_REL" reset -q --hard HEAD
        g "$DT_REL" clean -qf -- lineage_Tetris.mk
        die "$* (device tree rolled back; nothing was changed)"
    }
    grep -q '^PRODUCT_NAME := lineage_Tetris$' "$DT/lineage_Tetris.mk" \
        || fail "could not rewrite PRODUCT_NAME in lineage_Tetris.mk"
    grep -q 'vendor/lineage/config/common_full_phone\.mk' "$DT/lineage_Tetris.mk" \
        || fail "could not rewrite the common_full_phone inherit in lineage_Tetris.mk"
    grep -q 'lineage_Tetris\.mk' "$DT/AndroidProducts.mk" \
        || fail "could not point AndroidProducts.mk at lineage_Tetris.mk"
    local left
    left="$(grep -rIl -E '(vendor|device)/bliss/' --exclude-dir=.git "$DT" || true)"
    [[ -z "$left" ]] || fail "Bliss-only paths still referenced in: ${left//$TOP\//}"

    g "$DT_REL" add -A
    g "$DT_REL" commit -q -m "Tetris: Build as LineageOS" \
        -m "Generated by local_manifests_Tetris/apply-patches.sh from bliss_Tetris.mk."
    info "retargeted $DT_REL to lineage_Tetris"
}

apply_patches() {
    local dir proj patch name
    [[ -d "$HERE/patches" ]] || return 0
    while IFS= read -r dir; do
        proj="${dir#"$HERE/patches/"}"
        [[ -e "$TOP/$proj/.git" ]] || die "patches/$proj/ targets $proj, which is not a project in this tree"
        for patch in "$dir"/*.patch; do
            name="$proj/$(basename "$patch")"
            # Already applied if it reverses cleanly.
            if g "$proj" apply --reverse --check "$patch" >/dev/null 2>&1; then
                info "already applied: $name - skipped"
                continue
            fi
            if ! g "$proj" am -q --3way "$patch"; then
                g "$proj" am --abort >/dev/null 2>&1 || true
                die "$name no longer applies - rebase it, or move it to pending/ (see README)"
            fi
            info "applied: $name"
        done
    done < <(find "$HERE/patches" -type f -name '*.patch' -exec dirname {} \; | sort -u)
}

retarget_device_tree
apply_patches
info "done"
